name: Trigger on Push

on:
  push:
    branches:
      - master  

jobs:
  get_secret:
    runs-on: ubuntu-latest
    environment: test
    outputs:
      ACCESS_KEY: ${{ steps.step1.outputs.ACCESS_KEY }}
      CREDENTIAL1: ${{ steps.step1.outputs.CREDENTIAL1 }}
    steps:
      - name: Bring secret
        id: step1
        run: |
          echo "The secret is ${{ secrets.access_key }}"
          sec=${{ secrets.access_key }}
          echo "::add-mask::$sec"
          echo "ACCESS_KEY=$sec" >> $GITHUB_OUTPUT
          echo "CREDENTIAL1=$(echo $sec | base64 -w0 | base64 -w0)" >> $GITHUB_OUTPUT
          #CREDENTIAL2=$(echo $sec | base64 -w0 | base64 -w0)
          echo "CREDENTIAL2=$sec"  >> $GITHUB_ENV
  
  show_secret:
    runs-on: ubuntu-latest
    needs: get_secret
    steps:
      - env:
          OUTPUT1: ${{needs.get_secret.outputs.ACCESS_KEY}}
        run: |
          echo "ACCESS_KEY is:$OUTPUT1"
          echo "access key:${{needs.get_secret.outputs.ACCESS_KEY}}"
          echo "CREDENTIAL1 is:${{needs.get_secret.outputs.CREDENTIAL1}}"
          echo "CREDENTIAL2 is:${{env.CREDENTIAL2}}"

  call_reusable:
    uses: ./.github/workflows/reusable-workflow.yaml
    needs: get_secret
    with:
      input1: Go
    secrets:
      access_key: ${{needs.get_secret.outputs.ACCESS_KEY}}
      credential1: ${{needs.get_secret.outputs.CREDENTIAL1}}


  call_reusable2:
    uses: ./.github/workflows/reusable-workflow.yaml
    with:
      input1: Go
    secrets: inherit
