name: Trigger on Push

on:
  push:
    branches:
      - master  

jobs:
  get_secret:
    runs-on: ubuntu-latest
    environment: test
    outputs:
      ACCESS_KEY: ${{ steps.step1.outputs.ACCESS_KEY }}
    steps:
      - name: Bring secret
        id: step1
        run: |
          echo "The secret is ${{ secrets.access_key }}"
          sec=${{ secrets.access_key }}
          echo "::add-mask::$sec"
          echo "ACCESS_KEY=$sec" >> "$GITHUB_OUTPUT"
  
  show_secret:
    runs-on: ubuntu-latest
    needs: get_secret
    steps:
      - env:
          OUTPUT1: ${{needs.get_secret.outputs.ACCESS_KEY}}
        run: |
          echo "$ACCESS_KEY is:$OUTPUT1"

  call_reusable:
    uses: ./.github/workflows/reusable-workflow.yaml
    needs: get_secret
    with:
      input1: Go
    secrets:
      access_key: ${{needs.get_secret.outputs.ACCESS_KEY}}
