name: Reusable Workflow

on:
  workflow_call:
    inputs:
      input1:
        required: true
        type: string
      deploy_environment:
        required: false
        default: ' '
        type: string
    secrets:
      access_key:
        required: true
      credential1:
        required: true
        

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:  ${{ inputs.deploy_environment }}" 
    steps:
      - name: Use secret
        run: |
          echo "Input1 is: ${{ inputs.input1 }}" 
          echo "The secret is ${{ secrets.access_key }}"
          echo "The credential1 is ${{ secrets.credential1 }}"
          echo ${{ secrets.credential1 }} | base64 -d | base64 -d

