name: Reusable Workflow

on:
  workflow_call:
    inputs:
      input1:
        required: true
        type: string
    secrets:
      access_key:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Use secret
        run: echo "The secret is ${{ secrets.access_key }}"
